// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateContainer(arg1:docker.CreateContainerRequest):Promise<docker.CreateContainerResult>;

export function GetContainerLogs(arg1:string,arg2:number):Promise<string>;

export function GetContainerStats(arg1:string):Promise<docker.ContainerStats>;

export function GetDiskUsage():Promise<docker.DiskUsageSummary>;

export function GetOverview():Promise<docker.SystemOverview>;

export function ListContainers(arg1:boolean):Promise<Array<docker.ContainerInfo>>;

export function ListImages():Promise<Array<docker.ImageInfo>>;

export function PauseContainer(arg1:string):Promise<void>;

export function PruneImages(arg1:boolean):Promise<docker.PruneResult>;

export function PullImage(arg1:string):Promise<void>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function RestartNetwork(arg1:string):Promise<void>;

export function RestartStack(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartNetwork(arg1:string):Promise<void>;

export function StartStack(arg1:string):Promise<void>;

export function StartTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<docker.TerminalStartResult>;

export function StopContainer(arg1:string):Promise<void>;

export function StopNetwork(arg1:string):Promise<void>;

export function StopStack(arg1:string):Promise<void>;

export function UnpauseContainer(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
