// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function GetContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetContainerLogs'](arg1, arg2);
}

export function GetContainerStats(arg1) {
  return window['go']['main']['App']['GetContainerStats'](arg1);
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function PauseContainer(arg1) {
  return window['go']['main']['App']['PauseContainer'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3, arg4);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function UnpauseContainer(arg1) {
  return window['go']['main']['App']['UnpauseContainer'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
