// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateContainer(arg1) {
  return window['go']['main']['App']['CreateContainer'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetContainerLogs(arg1, arg2) {
  return window['go']['main']['App']['GetContainerLogs'](arg1, arg2);
}

export function GetContainerStats(arg1) {
  return window['go']['main']['App']['GetContainerStats'](arg1);
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetOverview() {
  return window['go']['main']['App']['GetOverview']();
}

export function InspectContainer(arg1) {
  return window['go']['main']['App']['InspectContainer'](arg1);
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PauseContainer(arg1) {
  return window['go']['main']['App']['PauseContainer'](arg1);
}

export function PruneImages(arg1) {
  return window['go']['main']['App']['PruneImages'](arg1);
}

export function PullImage(arg1) {
  return window['go']['main']['App']['PullImage'](arg1);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function RemoveImage(arg1, arg2) {
  return window['go']['main']['App']['RemoveImage'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartContainer(arg1) {
  return window['go']['main']['App']['RestartContainer'](arg1);
}

export function RestartNetwork(arg1) {
  return window['go']['main']['App']['RestartNetwork'](arg1);
}

export function RestartStack(arg1) {
  return window['go']['main']['App']['RestartStack'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['main']['App']['StartContainer'](arg1);
}

export function StartNetwork(arg1) {
  return window['go']['main']['App']['StartNetwork'](arg1);
}

export function StartStack(arg1) {
  return window['go']['main']['App']['StartStack'](arg1);
}

export function StartTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3, arg4);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function StopNetwork(arg1) {
  return window['go']['main']['App']['StopNetwork'](arg1);
}

export function StopStack(arg1) {
  return window['go']['main']['App']['StopStack'](arg1);
}

export function UnpauseContainer(arg1) {
  return window['go']['main']['App']['UnpauseContainer'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
