// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {network} from '../models';
import {image} from '../models';
import {system} from '../models';
import {volume} from '../models';
import {terminal} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectContainerToNetwork(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateContainer(arg1:container.CreateSpec):Promise<container.CreateResult>;

export function CreateNetwork(arg1:network.CreateNetworkSpec):Promise<string>;

export function DisconnectContainerFromNetwork(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetContainerLogs(arg1:string,arg2:number):Promise<string>;

export function GetContainerStats(arg1:string):Promise<container.Stats>;

export function GetDiskUsage():Promise<image.DiskUsageSummary>;

export function GetOverview():Promise<system.Overview>;

export function GetVolumeDiskUsage():Promise<volume.DiskUsageSummary>;

export function InspectContainer(arg1:string):Promise<string>;

export function InspectNetwork(arg1:string):Promise<string>;

export function InspectVolume(arg1:string):Promise<string>;

export function ListContainers(arg1:boolean):Promise<Array<container.Container>>;

export function ListImages():Promise<Array<image.Image>>;

export function ListNetworks():Promise<Array<network.Network>>;

export function ListVolumes():Promise<Array<volume.Volume>>;

export function OpenURL(arg1:string):Promise<void>;

export function PauseContainer(arg1:string):Promise<void>;

export function PruneImages(arg1:boolean):Promise<image.PruneResult>;

export function PruneNetworks():Promise<network.PruneResult>;

export function PruneVolumes():Promise<volume.PruneResult>;

export function PullImage(arg1:string):Promise<void>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImage(arg1:string,arg2:boolean):Promise<void>;

export function RemoveNetwork(arg1:string):Promise<void>;

export function RemoveVolume(arg1:string,arg2:boolean):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function RestartNetwork(arg1:string):Promise<void>;

export function RestartStack(arg1:string):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartNetwork(arg1:string):Promise<void>;

export function StartStack(arg1:string):Promise<void>;

export function StartTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<terminal.StartResult>;

export function StopContainer(arg1:string):Promise<void>;

export function StopNetwork(arg1:string):Promise<void>;

export function StopStack(arg1:string):Promise<void>;

export function UnpauseContainer(arg1:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
